version: '2'

services:
  storm-nimbus:
    image: jnonino/storm-nimbus
    environment:
      NIMBUS_HOST: "192.168.1.92"
      ZK: "192.168.1.92"
    ports:
      - "3772:3772"
      - "3773:3773"
      - "6627:6627"
  storm-ui:
    image: jnonino/storm-ui
    environment:
      HOST_NAME: "192.168.1.92"
      NIMBUS_HOST: "192.168.1.92"
      ZK: "192.168.1.92:2181,192.168.1.92:2182,192.168.1.92:2183"
    ports:
      - "8080:8080"
  storm-supervisor:
    image: jnonino/storm-supervisor
    environment:
      HOST_NAME: "192.168.1.92"
      NIMBUS_HOST: "192.168.1.92"
      ZK: "192.168.1.92"
    ports:
      - "6700:6700"
      - "6701:6701"
      - "6702:6702"
      - "6703:6703"
      - "8000:8000"