version: '2'

services:
  storm-nimbus:
    image: jnonino/storm-nimbus
    environment:
      NIMBUS_HOST: "<NIMBUS_HOST_IP>"
      ZK: "<ZOOKEEPER_NODE_IP>"
    ports:
      - "3772:3772"
      - "3773:3773"
      - "6627:6627"
  storm-ui:
    image: jnonino/storm-ui
    environment:
      HOST_NAME: "<UI_NODE_IP>"
      NIMBUS_HOST: "<NIMBUS_HOST_IP>"
      ZK: "<ZOOKEEPER_NODE_IP>:2181,<ZOOKEEPER_NODE_IP>:2182,<ZOOKEEPER_NODE_IP>:2183"
    ports:
      - "8080:8080"
  storm-supervisor:
    image: jnonino/storm-supervisor
    environment:
      HOST_NAME: "<SUPERVISOR_NODE_IP>"
      NIMBUS_HOST: "<NIMBUS_HOST_IP>"
      ZK: "<ZOOKEEPER_NODE_IP>"
    ports:
      - "6700:6700"
      - "6701:6701"
      - "6702:6702"
      - "6703:6703"
      - "8000:8000"