zookeeper:
  image: wurstmeister/zookeeper:3.4.6
  ports:
    - "2181"
kafka:
  image: wurstmeister/kafka:0.9.0.1
  ports:
    - "9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
    KAFKA_CREATE_TOPICS: "Argentina-Salta-Cafayate:1:1,Argentina-Catamarca-Aconquija:1:1,Argentina-Cordoba-RioSegundo:1:1,Argentina-Tucuman-AltoVerde:1:1,Argentina-Tucuman-PozoVerde:1:1,Argentina-SanJuan-Iglesia:1:1,Argentina-Cordoba-VillaAllende:1:1,Argentina-Mendoza-Agrelo:1:1,Argentina-Cordoba-ElAranado:1:1,Argentina-EntreRios-Diamante:1:1,Argentina-Cordoba-Luque:1:1,Argentina-LaRioja-Famatina:1:1,Argentina-Cordoba-Omixomlab:1:1,Argentina-Cordoba-Cordoba:1:1,Argentina-Cordoba-RioPrimero:1:1,Argentina-Chaco-Chaco:1:1,Argentina-SantaFe-Rosario:1:1,Argentina-EntreRios-Parana:1:1,Argentina-EntreRios-SantaElena:1:1,Argentina-Cordoba-RioCuarto:1:1,Argentina-Cordoba-SanJusto:1:1,Argentina-SantiagodelEstero-Banderas:1:1,Argentina-Mendoza-LujandeCuyo:1:1,Argentina-LaPampa-Maraco:1:1,Argentina-Cordoba-Unquillo:1:1,Argentina-Cordoba-Totoral:1:1,Argentina-BuenosAires-Pergamino:1:1,Argentina-Cordoba-JesusMaria:1:1,Argentina-Cordoba-SanMartin:1:1,Argentina-SantaFe-Castellanos:1:1,Argentina-Cordoba-LaPuerta:1:1,Argentina-Cordoba-RioSeco:1:1,Argentina-Mendoza-Beltran:1:1,Argentina-Cordoba-TerceroArriba:1:1,Argentina-Cordoba-SantaMaria:1:1,Argentina-Cordoba-GeneralRoca:1:1,Argentina-Cordoba-Colon:1:1,Argentina-Cordoba-GralRoca:1:1,Argentina-SanJuan-CanadaOnda:1:1"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

#nimbus:
#  image: wurstmeister/storm-nimbus:0.9.2
#  ports:
#    - "3773:3773"
#    - "3772:3772"
#    - "6627:6627"
#  links:
#    - zookeeper:zk
#supervisor:
#  image: wurstmeister/storm-supervisor:0.9.2
#  ports:
#    - "8000:8000"
#  links:
#    - nimbus:nimbus
#    - zookeeper:zk
#ui:
#  image: wurstmeister/storm-ui:0.9.2
#  ports:
#    - "8080:8080"
#  links:
#    - nimbus:nimbus
#    - zookeeper:zk