zookeeper:
  image: wurstmeister/zookeeper:3.4.6
  ports:
    - "2181:2181"
kafka:
  image: wurstmeister/kafka:0.9.0.1
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.0.107
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock