version: "2"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.9.0.1
    ports:
      - "9092:9092"
    links:
      - zookeeper:zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.59.103

#nimbus:
#  image: wurstmeister/storm-nimbus:0.9.2
#  ports:
#    - "3773:3773"
#    - "3772:3772"
#    - "6627:6627"
#  links:
#    - zookeeper:zk
#supervisor:
#  image: wurstmeister/storm-supervisor:0.9.2
#  ports:
#    - "8000:8000"
#  links:
#    - nimbus:nimbus
#    - zookeeper:zk
#ui:
#  image: wurstmeister/storm-ui:0.9.2
#  ports:
#    - "8080:8080"
#  links:
#    - nimbus:nimbus
#    - zookeeper:zk