version: '2'
services:
  zookeeper:
    image: oddpoet/zookeeper
    hostname: zookeeper
    command:
      - "2181"
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper:zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: 9092
  producer:
    build:
      context: ./kafka/.
      args:
        HOST_IP: "192.168.99.100"
    links:
      - kafka

#nimbus:
#  image: wurstmeister/storm-nimbus:0.9.2
#  ports:
#    - "3773:3773"
#    - "3772:3772"
#    - "6627:6627"
#  links:
#    - zookeeper:zk
#supervisor:
#  image: wurstmeister/storm-supervisor:0.9.2
#  ports:
#    - "8000:8000"
#  links:
#    - nimbus:nimbus
#    - zookeeper:zk
#ui:
#  image: wurstmeister/storm-ui:0.9.2
#  ports:
#    - "8080:8080"
#  links:
#    - nimbus:nimbus
#    - zookeeper:zk