kafka:
  image: spotify/kafka
  ports:
    - "2181"
    - "9092"
  environment:
    ADVERTISED_HOST: 192.168.99.100
    ADVERTISED_PORT: 9092
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock