version: '2'

services:
  kafka1:
    image: jnonino/kafka
    environment:
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "192.168.1.35:2181,192.168.1.35:2182,192.168.1.35:2183"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.35
    ports:
      - "9092:9092"
  kafka2:
    image: jnonino/kafka
    environment:
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: "192.168.1.35:2181,192.168.1.35:2182,192.168.1.35:2183"
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.35
    ports:
      - "9093:9092"
  kafka3:
    image: jnonino/kafka
    environment:
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: "192.168.1.35:2181,192.168.1.35:2182,192.168.1.35:2183"
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.35
    ports:
      - "9094:9092"